# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/stueckler/dev/octreelib

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/stueckler/dev/octreelib

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/stueckler/dev/octreelib/CMakeFiles /home/stueckler/dev/octreelib/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/stueckler/dev/octreelib/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named octreelib

# Build rule for target.
octreelib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 octreelib
.PHONY : octreelib

# fast build rule for target.
octreelib/fast:
	$(MAKE) -f CMakeFiles/octreelib.dir/build.make CMakeFiles/octreelib.dir/build
.PHONY : octreelib/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

src/octreelib/algorithm/downsample.o: src/octreelib/algorithm/downsample.cpp.o
.PHONY : src/octreelib/algorithm/downsample.o

# target to build an object file
src/octreelib/algorithm/downsample.cpp.o:
	$(MAKE) -f CMakeFiles/octreelib.dir/build.make CMakeFiles/octreelib.dir/src/octreelib/algorithm/downsample.cpp.o
.PHONY : src/octreelib/algorithm/downsample.cpp.o

src/octreelib/algorithm/downsample.i: src/octreelib/algorithm/downsample.cpp.i
.PHONY : src/octreelib/algorithm/downsample.i

# target to preprocess a source file
src/octreelib/algorithm/downsample.cpp.i:
	$(MAKE) -f CMakeFiles/octreelib.dir/build.make CMakeFiles/octreelib.dir/src/octreelib/algorithm/downsample.cpp.i
.PHONY : src/octreelib/algorithm/downsample.cpp.i

src/octreelib/algorithm/downsample.s: src/octreelib/algorithm/downsample.cpp.s
.PHONY : src/octreelib/algorithm/downsample.s

# target to generate assembly for a file
src/octreelib/algorithm/downsample.cpp.s:
	$(MAKE) -f CMakeFiles/octreelib.dir/build.make CMakeFiles/octreelib.dir/src/octreelib/algorithm/downsample.cpp.s
.PHONY : src/octreelib/algorithm/downsample.cpp.s

src/octreelib/feature/normalestimation.o: src/octreelib/feature/normalestimation.cpp.o
.PHONY : src/octreelib/feature/normalestimation.o

# target to build an object file
src/octreelib/feature/normalestimation.cpp.o:
	$(MAKE) -f CMakeFiles/octreelib.dir/build.make CMakeFiles/octreelib.dir/src/octreelib/feature/normalestimation.cpp.o
.PHONY : src/octreelib/feature/normalestimation.cpp.o

src/octreelib/feature/normalestimation.i: src/octreelib/feature/normalestimation.cpp.i
.PHONY : src/octreelib/feature/normalestimation.i

# target to preprocess a source file
src/octreelib/feature/normalestimation.cpp.i:
	$(MAKE) -f CMakeFiles/octreelib.dir/build.make CMakeFiles/octreelib.dir/src/octreelib/feature/normalestimation.cpp.i
.PHONY : src/octreelib/feature/normalestimation.cpp.i

src/octreelib/feature/normalestimation.s: src/octreelib/feature/normalestimation.cpp.s
.PHONY : src/octreelib/feature/normalestimation.s

# target to generate assembly for a file
src/octreelib/feature/normalestimation.cpp.s:
	$(MAKE) -f CMakeFiles/octreelib.dir/build.make CMakeFiles/octreelib.dir/src/octreelib/feature/normalestimation.cpp.s
.PHONY : src/octreelib/feature/normalestimation.cpp.s

src/octreelib/spatialaggregate/octree.o: src/octreelib/spatialaggregate/octree.cpp.o
.PHONY : src/octreelib/spatialaggregate/octree.o

# target to build an object file
src/octreelib/spatialaggregate/octree.cpp.o:
	$(MAKE) -f CMakeFiles/octreelib.dir/build.make CMakeFiles/octreelib.dir/src/octreelib/spatialaggregate/octree.cpp.o
.PHONY : src/octreelib/spatialaggregate/octree.cpp.o

src/octreelib/spatialaggregate/octree.i: src/octreelib/spatialaggregate/octree.cpp.i
.PHONY : src/octreelib/spatialaggregate/octree.i

# target to preprocess a source file
src/octreelib/spatialaggregate/octree.cpp.i:
	$(MAKE) -f CMakeFiles/octreelib.dir/build.make CMakeFiles/octreelib.dir/src/octreelib/spatialaggregate/octree.cpp.i
.PHONY : src/octreelib/spatialaggregate/octree.cpp.i

src/octreelib/spatialaggregate/octree.s: src/octreelib/spatialaggregate/octree.cpp.s
.PHONY : src/octreelib/spatialaggregate/octree.s

# target to generate assembly for a file
src/octreelib/spatialaggregate/octree.cpp.s:
	$(MAKE) -f CMakeFiles/octreelib.dir/build.make CMakeFiles/octreelib.dir/src/octreelib/spatialaggregate/octree.cpp.s
.PHONY : src/octreelib/spatialaggregate/octree.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... octreelib"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... src/octreelib/algorithm/downsample.o"
	@echo "... src/octreelib/algorithm/downsample.i"
	@echo "... src/octreelib/algorithm/downsample.s"
	@echo "... src/octreelib/feature/normalestimation.o"
	@echo "... src/octreelib/feature/normalestimation.i"
	@echo "... src/octreelib/feature/normalestimation.s"
	@echo "... src/octreelib/spatialaggregate/octree.o"
	@echo "... src/octreelib/spatialaggregate/octree.i"
	@echo "... src/octreelib/spatialaggregate/octree.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

